#import "order-fragment.graphql"
#import "../error.graphql"
#import "../validation-error.graphql"

mutation CoreShopRemoveOrderVoucherCode($voucherCode: String!, $token: String!) {
    CoreShopRemoveOrderVoucherCode(removeOrderVoucherCode: {order: {token: $token}, orderVoucherCode: {code: $voucherCode}}) {
        ... on CoreShopRemoveOrderVoucherCodeResult {
            __typename
            order {
                ...order
            }
        }
        ... on CoreShopError {
            ...error
        }
        ... on CoreShopValidationError {
            ...validation_error
        }
    }
}