ARG NODE_VERSION=22

FROM node:${NODE_VERSION}-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund

ARG API_HOSTNAME=enterprise.coreshop.dev
ENV API_HOSTNAME=$API_HOSTNAME
ARG NEXT_PUBLIC_PIMCORE_BASE_URL=https://enterprise.coreshop.dev
ENV NEXT_PUBLIC_PIMCORE_BASE_URL=$NEXT_PUBLIC_PIMCORE_BASE_URL

COPY . .
RUN npm run build-storybook

FROM nginx:1.28-alpine AS runner
COPY --from=builder /app/storybook-static /usr/share/nginx/html
