#import "../error.graphql"

query getCoreShopMe {
    CoreShopMe {
        ... on CoreShopMeResult {
            __typename
            user {
                id
                ... on object_CoreShopUser {
                    customer {
                        ... on object_CoreShopCustomer {
                            id
                            salutation
                            firstname
                            lastname
                            email
                            gender
                            newsletterActive
                        }
                    }
                }
            }
        }
        ... on CoreShopError {
            ...error
        }
    }
}