#import "../error.graphql"
#import "../address/address-fragment.graphql"
query getCoreShopMe {
    CoreShopMe {
        ... on CoreShopMeResult {
            __typename
            user {
                id
                ... on object_CoreShopUser {
                    customer {
                        ... on object_CoreShopCustomer {
                            id
                            salutation
                            firstname
                            lastname
                            email
                            gender
                            newsletterActive
                            defaultAddress {
                                ... on object_CoreShopAddress {
                                    id
                                }
                            }
                        }
                    }
                }
            }
        }
        ... on CoreShopError {
            ...error
        }
    }
}