#import "../error.graphql"
#import "../validation-error.graphql"
mutation CoreShopUpdateMe(
    $salutation: String!
    $gender: String!
    $firstname: String!
    $lastname: String!
    $newsletterActive: Boolean!
    $defaultAddressId: Int!
) {
    CoreShopUpdateMe(updateMe: {
        me: {
            salutation: $salutation,
            gender: $gender,
            firstname: $firstname,
            lastname: $lastname,
            newsletterActive: $newsletterActive,
            defaultAddressId: $defaultAddressId
        }
    }) {
        __typename
        ... on CoreShopUpdateMeResult {
            me {
                salutation
                gender
                firstname
                lastname
                newsletterActive
                defaultAddress {
                    ... on object_CoreShopAddress {
                        id
                    }
                }
            }
        }
        ... on CoreShopError {
            ...error
        }
        ... on CoreShopValidationError {
            ...validation_error
        }
    }
}