#import "../error.graphql"
#import "category-fragment.graphql"

query getCoreShopCategories {
    CoreShopCategories(categoryListing: {}) {
        ... on CoreShopCategoriesResult {
            __typename
            categories {
                totalCount,
                edges {
                    __typename
                    node {
                        ...category
                    }
                }
            }
        }
        ... on CoreShopError {
            ...error
        }
    }
}