#import "product-fragment.graphql"
#import "../error.graphql"

query getCoreShopProduct($productId: Int!) {
    CoreShopProduct(product: { productId: $productId }) {
        ... on CoreShopProductResult {
            __typename
            product {
                ...product
                variantAttributeIndex {
                    ... on CoreShopVariantAttributeIndex {
                        url
                        productId
                        attributes {
                            ... on CoreShopVariantAttributeIndexAttribute {groupId, attributeId}
                        }
                    }
                }
            }
        }
        ... on CoreShopError {
            ...error
        }
    }
}
