query CoreShopCarrierList(
    $token: String!
) {
    CoreShopCarrierList(carrierList: {order: {token: $token}}) {
        __typename
        ... on CoreShopCarrierListResult{
            carriers {
                carrier {
                    id
                    identifier
                    translations {
                        items {
                            title
                            description
                        }
                    }
                }
                price_net
                price_gross
                tax
            }
        }
    }
}