#import "../order/order-fragment.graphql"
#import "../error.graphql"
#import "../validation-error.graphql"

mutation CoreShopCheckoutPaymentProvider(
    $token: String!
    $paymentProvider: PaymentProviderEnumType!
) {
    CoreShopCheckoutPaymentProvider(checkoutPaymentProvider: {order: {token: $token}, paymentProvider: $paymentProvider}) {
        ... on CoreShopCheckoutPaymentProviderResult {
            __typename
            order {
                ...order
            }
        }
        ... on CoreShopError {
            ...error
        }
        ... on CoreShopValidationError {
            ...validation_error
        }
    }
}